example.property: "I AM IN THE DEFAULT"
spring.jpa.database: "POSTGRESQL"
spring.datasource.platform:  "postgres"
spring.jpa.show-sql: "true"
spring.database.driverClassName: "org.postgresql.Driver"
spring.datasource.driver-class-name: "org.postgresql.Driver"
spring.datasource.url: "jdbc:postgresql://database:5432/eagle_eye_local"
spring.datasource.username: "postgres"
spring.datasource.password: "{cipher}AQBEePJcpztf7FVw67BiPc4qMb8zoAjPRZ8yhb9NrbKbtRD1KXRIr9v2qwVBrO7ayc2fYQ/F0KHYq3OKao5fnlanrxCNtibFwSqhkCpf3bb5SF3Y5Wm0JI5hnrAa18XR1+RvDAnhUdtOa5w6g1Urn5j8ynShwPNJ//Bqa1DCbzJv96uau8S0EYuU/zeoyxuhOkmOsO5luxzttW/vfpB7MgENl4MKCgRE36zbbauZQ7z0YCl27ywH5GYP9HO1QkEzEfVSDlO3890tdXUq84hEH4adtQFAcROsND0SLuP1ewELc8a0Ar+MkBP25gyG0tS4HJmhsA7AcpyhgwNrkvwzuAxLQxTpTaJnbzrGMBUDEdzTpm4x7VEc6KXzFVmLDWa/Ve0="
spring.datasource.testWhileIdle: "true"
spring.datasource.validationQuery: "SELECT 1"
spring.jpa.properties.hibernate.dialect: "org.hibernate.dialect.PostgreSQLDialect"
redis.server: "redis"
redis.port: "6379"
redis.host: "redis"
eureka.client.service-url.defaultZone: http://eurekaserver:8761/eureka/
eureka.client.fetchRegistry: true
eureka.client.registerWithEureka: true
eureka.instance.preferIpAddress: true
eureka.client.serviceUrl.defaultZone: http://eurekaserver:8761/eureka/
ribbon.eager-load.enabled: true
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults: false
spring.datasource.initialization-mode: always
security.jwt.key-store: classpath:server.jks
security.jwt.key-store-password: "{cipher}AQAkUqE5QOXKxCVCrJlRHmkTeESjZm1eks5gPvV8W0QMObTuaxl5HdnJIA4JQRpBl7wheunzxlpR0ZzTQjrJkRdAuidJap9rT8M3CXzUv0F95vNsL5ZUdKy9EK3hqcoo39bNl1TWx9NOO2Vll1OiYl6lyBWRsPMUqLhH7Kq0HAiOQKPFVzVtNJ3GG05ehJEcBqwwsKzWRFw1SWMViFxCNZI1ij90s1NQyiXWRgZ68lE1sblVFC7o0TRiPZAqKPGTp++na1bjBw7HN+sZzy8rFI9AA0VEutnRVNS/Pk+3irQrl1CFgVVRmJMYYPwRZTJPDaEbhYQMn/NJrNVyaMkI2uy7TDFDhO2uaHEycP6/+VbdGshHY0s/XuI4pW56neG/w68="
security.jwt.key-pair-alias: mytestkey
security.jwt.key-pair-password: "{cipher}AQAkUqE5QOXKxCVCrJlRHmkTeESjZm1eks5gPvV8W0QMObTuaxl5HdnJIA4JQRpBl7wheunzxlpR0ZzTQjrJkRdAuidJap9rT8M3CXzUv0F95vNsL5ZUdKy9EK3hqcoo39bNl1TWx9NOO2Vll1OiYl6lyBWRsPMUqLhH7Kq0HAiOQKPFVzVtNJ3GG05ehJEcBqwwsKzWRFw1SWMViFxCNZI1ij90s1NQyiXWRgZ68lE1sblVFC7o0TRiPZAqKPGTp++na1bjBw7HN+sZzy8rFI9AA0VEutnRVNS/Pk+3irQrl1CFgVVRmJMYYPwRZTJPDaEbhYQMn/NJrNVyaMkI2uy7TDFDhO2uaHEycP6/+VbdGshHY0s/XuI4pW56neG/w68="
logging.level.com.thoughtmechanix: DEBUG
ribbon.eager-load.clients: authenticationservice, organizationservice, licensingservice, specialroutesservice