spring:
  cloud:
    stream:
      bindings:
        output:
            destination:  orgChangeTopic
            content-type: application/json
      kafka:
          binder:
            zkNodes: zookeeper:2181
            brokers: kafkaserver:29092
            defaultZkPort: 2181
            defaultBrokerPort: 29092
security:
  jwt:
    public-key: classpath:public.txt  
logging:
  file:
    path: .
    name: ${application.name}.log    